In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import plotly.graph_objects as go

In [2]:
intapp = pd.read_csv('Internship_ApplicationsA.csv')
intapp.tail() # I checked head and it showed the first 5, i just wanted to make sure it was 
#showing the most current which it is, I don't remember doing .tail i class but it's what seemed
#logical to me and it worked

,Submission Date,Advising \nApproval Response,Advising Approval \nResponse Date,Advising Comments,Advisor,Internship Coordinator \nApproval Response,Internship Coordinator \nApproval Response Date,Internship Coordinator Comments,Internship Coordinator,Advising/Tyler Registration Comments,...,Total Work Hours for Semester,Requested Credit Hours,"In-person, Remote, Hybrid",Paid Internship?,Salary,Internship Job Title,Description of Job Responsibilities,How will the internship prepare them for professional practice in their major?,Offered FT?,Acceepted FT?
927,4/6/26,Approve,2026-04-07T13:59:37Z,NaN,"Hansen, Ellie",Approve,2026-04-08T15:06:55Z,Approving but hours need to be changed to 45,"Dowling, Kristin",NaN,...,32.0,3.0,In-person,No,NaN,Student,Designing a product for a non-profit with othe...,With the project that helps a non-profit organ...,NaN,NaN
928,4/8/26,Approve,2026-04-08T17:53:04Z,NaN,"Hansen, Ellie",Approve,2026-04-08T19:26:42Z,The student got a different internship. No nee...,"Knepper, Caitlin",This is a different internship than the one su...,...,150.0,1.0,Remote,No,NaN,Intern,Editing and organizing footage,It will give me real world experience,NaN,NaN
929,4/8/26,Approve,2026-04-08T19:25:51Z,NaN,"Hansen, Ellie",Approve,2026-04-09T12:23:38Z,NaN,"Jeffries, Lauren",NaN,...,288.0,1.0,In-person,Yes,$20 an hour,Marketing Communications Intern,"There is an over-arching website project, wher...",This internship will help me improve in areas ...,NaN,NaN
930,4/9/26,Approve,2026-04-09T17:25:45Z,NaN,"Hansen, Ellie",Approve,2026-04-13T13:19:24Z,Hours will be 450,"Jeffries, Lauren",NaN,...,420.0,3.0,Remote,No,NaN,Internship/Apprenticeship program,I will be working on an independent assingment...,This internship will help me learn hands-on ti...,NaN,NaN
931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
len(intapp)

932

In [3]:
intapp.columns #I wanted to make sure I know all of the columns and need to decide which are most interesting
#I know the school director wants to see where students are getting internships, I think it would be good to see 
# the numbers of students getting internships by year (but maybe not) I did add the last 2 columns which we do not currently track so these are fake

Index(['Submission Date', 'Advising \nApproval Response',
       'Advising Approval \nResponse Date', 'Advising Comments', 'Advisor',
       'Internship Coordinator \nApproval Response',
       'Internship Coordinator \nApproval Response Date',
       'Internship Coordinator Comments', 'Internship Coordinator',
       'Advising/Tyler Registration Comments', 'Registration Date',
       'Semester Student Registered', 'Student \nFirst Name',
       'Student \nLast Name', 'KSU Email', 'Phone Number', 'CCI Major',
       'Organization Name', 'Description of Organization',
       'Organization Street Address', 'Organization City',
       'Organization State', 'Organization Country (if applicable)',
       'Organization Zip', 'Organization Contact Info', 'Organization Website',
       'Supervisor Name', 'Supervisor Email', 'Supervisor Phone Number',
       'Supervisor Job Title', 'Internship Start Date', 'Internship End Date',
       'Total Number of Weeks Working', 'Work Hours Per Week',
       'Total Work Hours for Semester', 'Requested Credit Hours',
       'In-person, Remote, Hybrid', 'Paid Internship?', 'Salary',
       'Internship Job Title', 'Description of Job Responsibilities',
       'How will the internship prepare them for professional practice in their major?',
       'Offered FT?', 'Acceepted FT?'],
      dtype='object')

In [4]:
type(intapp['Organization Name'].iloc[0])

str

In [5]:
intappdata = pd.DataFrame(intapp['Organization Name'])

intappdata.head(10)

                                   Organization Name
0      CAPS - Counseling and Psychological services
1                                         Mail Pro 1
2                     Stow Munroe Falls City Schools
3                                         Kent Wired
4                 KENT STATE ATHLETIC COMMUNICATIONS
5  College of Communication and Information Kent ...
6                                   Playhouse Square
7                           West County News Journal
8                              Christ Baptist Church
9                                              Fox 8

In [6]:
intappdata = pd.DataFrame(intapp['Internship Job Title'])

intappdata.head(10)

             Internship Job Title
0  Social media/marketing intern
1                       Designer
2         Public Relations Intern
3            Designer/Illustrator
4   Athletic Communication Intern
5                Student Interns
6           Graphic Design Intern
7                     News Intern
8                    Web Designer
9   Friday Night Touchdown Intern

In [7]:
intappdata = pd.DataFrame(intapp['CCI Major'])

intappdata.head(10)

                                 CCI Major
0                    Communication Studies
1  Visual Communication Design (BFA or BA)
2                    Communication Studies
3  Visual Communication Design (BFA or BA)
4                    Communication Studies
5                    Communication Studies
6  Visual Communication Design (BFA or BA)
7                               Journalism
8            Emerging Media and Technology
9                    Communication Studies

In [8]:
intappdata = pd.DataFrame(intapp['Organization State'])

intappdata.head(10)

  Organization State
0               Ohio
1               Ohio
2               Ohio
3               Ohio
4               Ohio
5               Ohio
6               Ohio
7       Pennsylvania
8               Ohio
9               Ohio

In [18]:
intappdata = pd.DataFrame(intapp['Semester Student Registered'])

intappdata.head(10)

  Semester Student Registered
0                   Fall 2023
1                 Summer 2023
2                   Fall 2023
3                   Fall 2023
4                   Fall 2023
5                   Fall 2023
6                 Summer 2023
7                   Fall 2023
8                   Fall 2023
9                         NaN