In [70]:
import pandas as pd
from matplotlib import pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [71]:
intapp = pd.read_csv('Internship_ApplicationsA.csv')
intapp.tail() # I checked head and it showed the first 5, i just wanted to make sure it was 
#showing the most current which it is, I don't remember doing .tail i class but it's what seemed
#logical to me and it worked

,Submission Date,Advising \nApproval Response,Advising Approval \nResponse Date,Advising Comments,Advisor,Internship Coordinator \nApproval Response,Internship Coordinator \nApproval Response Date,Internship Coordinator Comments,Internship Coordinator,Advising/Tyler Registration Comments,...,Total Work Hours for Semester,Requested Credit Hours,"In-person, Remote, Hybrid",Paid Internship?,Salary,Internship Job Title,Description of Job Responsibilities,How will the internship prepare them for professional practice in their major?,Offered FT?,Acceepted FT?
927,4/6/26,Approve,2026-04-07T13:59:37Z,NaN,"Hansen, Ellie",Approve,2026-04-08T15:06:55Z,Approving but hours need to be changed to 45,"Dowling, Kristin",NaN,...,32.0,3.0,In-person,No,NaN,Student,Designing a product for a non-profit with othe...,With the project that helps a non-profit organ...,NaN,NaN
928,4/8/26,Approve,2026-04-08T17:53:04Z,NaN,"Hansen, Ellie",Approve,2026-04-08T19:26:42Z,The student got a different internship. No nee...,"Knepper, Caitlin",This is a different internship than the one su...,...,150.0,1.0,Remote,No,NaN,Intern,Editing and organizing footage,It will give me real world experience,NaN,NaN
929,4/8/26,Approve,2026-04-08T19:25:51Z,NaN,"Hansen, Ellie",Approve,2026-04-09T12:23:38Z,NaN,"Jeffries, Lauren",NaN,...,288.0,1.0,In-person,Yes,$20 an hour,Marketing Communications Intern,"There is an over-arching website project, wher...",This internship will help me improve in areas ...,NaN,NaN
930,4/9/26,Approve,2026-04-09T17:25:45Z,NaN,"Hansen, Ellie",Approve,2026-04-13T13:19:24Z,Hours will be 450,"Jeffries, Lauren",NaN,...,420.0,3.0,Remote,No,NaN,Internship/Apprenticeship program,I will be working on an independent assingment...,This internship will help me learn hands-on ti...,NaN,NaN
931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
len(intapp) # I want to know the number of l

932

In [73]:
type(intapp)

pandas.core.frame.DataFrame

In [74]:
intapp.columns #I wanted to make sure I know all of the columns and need to decide which are most interesting
#I know the school director wants to see where students are getting internships, I think it would be good to see 
# the numbers of students getting internships by year (but maybe not) I did add the last 2 columns which we do not currently track so these are fake

Index(['Submission Date', 'Advising \nApproval Response',
       'Advising Approval \nResponse Date', 'Advising Comments', 'Advisor',
       'Internship Coordinator \nApproval Response',
       'Internship Coordinator \nApproval Response Date',
       'Internship Coordinator Comments', 'Internship Coordinator',
       'Advising/Tyler Registration Comments', 'Registration Date',
       'Semester Student Registered', 'Student \nFirst Name',
       'Student \nLast Name', 'KSU Email', 'Phone Number', 'CCI Major',
       'Organization Name', 'Description of Organization',
       'Organization Street Address', 'Organization City',
       'Organization State', 'Organization Country (if applicable)',
       'Organization Zip', 'Organization Contact Info', 'Organization Website',
       'Supervisor Name', 'Supervisor Email', 'Supervisor Phone Number',
       'Supervisor Job Title', 'Internship Start Date', 'Internship End Date',
       'Total Number of Weeks Working', 'Work Hours Per Week',
       'Total Work Hours for Semester', 'Requested Credit Hours',
       'In-person, Remote, Hybrid', 'Paid Internship?', 'Salary',
       'Internship Job Title', 'Description of Job Responsibilities',
       'How will the internship prepare them for professional practice in their major?',
       'Offered FT?', 'Acceepted FT?'],
      dtype='object')

In [75]:
type(intapp['Organization Name'].iloc[0])

str

In [76]:
intappdata = pd.DataFrame(intapp['Organization Name'])

intappdata.head(10)

                                   Organization Name
0      CAPS - Counseling and Psychological services
1                                         Mail Pro 1
2                     Stow Munroe Falls City Schools
3                                         Kent Wired
4                 KENT STATE ATHLETIC COMMUNICATIONS
5  College of Communication and Information Kent ...
6                                   Playhouse Square
7                           West County News Journal
8                              Christ Baptist Church
9                                              Fox 8

In [77]:
intapp.groupby('Organization Name').count()['Submission Date']

Organization Name
 Chambers of Commerce                                         1
 Greater Cleveland Automobile Dealers’ Association (GCADA)    1
 In Step With Horses(ISWH) and American Tire Works(ATW)       1
10k Movement                                                  1
1895 FILMA                                                    1
                                                             ..
martinwolf                                                    1
ohio employee ownership center                                1
peaches and cream                                             1
red point digital                                             1
s                                                             1
Name: Submission Date, Length: 733, dtype: int64

In [78]:
intapp.groupby('Organization Zip').count()['Submission Date'].sort_values(ascending = False)[0:20]

Organization Zip
44240    89
44242    87
44304    26
44224    22
44115    21
44308    17
44313    17
44114    16
44720    14
44139    14
44311    13
44145    13
44243    13
44125    12
44236    12
44266    12
44087     9
44107     9
44131     8
44103     7
Name: Submission Date, dtype: int64

In [79]:
intappdata = pd.DataFrame(intapp['Internship Job Title'])

intappdata.head(10)

             Internship Job Title
0  Social media/marketing intern
1                       Designer
2         Public Relations Intern
3            Designer/Illustrator
4   Athletic Communication Intern
5                Student Interns
6           Graphic Design Intern
7                     News Intern
8                    Web Designer
9   Friday Night Touchdown Intern

In [80]:
intapp['Internship Job Title'].head(10)

0    Social media/marketing intern
1                         Designer
2           Public Relations Intern
3              Designer/Illustrator
4     Athletic Communication Intern
5                  Student Interns
6             Graphic Design Intern
7                       News Intern
8                      Web Designer
9     Friday Night Touchdown Intern
Name: Internship Job Title, dtype: object

In [81]:
intappdata = pd.DataFrame(intapp['CCI Major'])

intappdata.head(10)

                                 CCI Major
0                    Communication Studies
1  Visual Communication Design (BFA or BA)
2                    Communication Studies
3  Visual Communication Design (BFA or BA)
4                    Communication Studies
5                    Communication Studies
6  Visual Communication Design (BFA or BA)
7                               Journalism
8            Emerging Media and Technology
9                    Communication Studies

In [82]:
intappdata = pd.DataFrame(intapp['Organization State'])

intappdata.head(10)

  Organization State
0               Ohio
1               Ohio
2               Ohio
3               Ohio
4               Ohio
5               Ohio
6               Ohio
7       Pennsylvania
8               Ohio
9               Ohio

In [83]:
intappdata = pd.DataFrame(intapp['Organization State'])

intappdata.head(10)

  Organization State
0               Ohio
1               Ohio
2               Ohio
3               Ohio
4               Ohio
5               Ohio
6               Ohio
7       Pennsylvania
8               Ohio
9               Ohio

In [84]:
intapp.groupby('Organization State').count()['Submission Date'].sort_values(ascending = False)[0:60]

Organization State
Ohio               726
California          32
New York            31
International       25
Pennsylvania        22
Massachusetts       11
Virginia             9
Wisconsin            7
Colorado             6
Georgia              6
Washington           6
Texas                6
Connecticut          5
Florida              5
Indiana              5
New Jersey           4
Arizona              3
Missouri             3
Michigan             3
Nevada               2
Maryland             2
Kentucky             2
Illinois             2
Washington D.C.      2
North Carolina       1
Maine                1
Oklahoma             1
Louisiana            1
Tennessee            1
Idaho                1
Name: Submission Date, dtype: int64

In [85]:
intapp.groupby('Internship Job Title').count()['Submission Date'].sort_values(ascending = False)[0:10]

Internship Job Title
Graphic Design Intern      42
Intern                     31
Graphic Designer           28
Marketing Intern           25
Social Media Intern        13
Communications Intern      12
Video Production Intern    11
Video Editor               11
Public Relations Intern    11
Photographer               10
Name: Submission Date, dtype: int64

In [86]:
intappdata = pd.DataFrame(intapp['Semester Student Registered'])

intappdata.head(10)

  Semester Student Registered
0                   Fall 2023
1                 Summer 2023
2                   Fall 2023
3                   Fall 2023
4                   Fall 2023
5                   Fall 2023
6                 Summer 2023
7                   Fall 2023
8                   Fall 2023
9                         NaN

In [87]:
#how do i get the number of students per semester?
intapp.groupby('Semester Student Registered').count()['Submission Date'].sort_values(ascending = False)

Semester Student Registered
Summer 2024    159
Summer 2025    137
Spring 2026     93
Spring 2024     89
Fall 2025       77
Spring 2025     69
Fall 2024       67
Fall 2023       62
Summer 2026     38
Fall 2026       11
Summer 2023      3
Name: Submission Date, dtype: int64

In [ ]:
semester_counts = intapp.groupby('Semester Student Registered').size().sort_index()
#I think Professor Silva helped me with this during office hours

In [97]:
#looked at plotly group 1's first bar graph for this part

fig = px.bar(x=semester_counts.index,y=semester_counts.values,labels={'x': 'Semester', 'y': 'Number of Students'},
    title='Students in Internships per Semester')

fig.show()

In [90]:
#replicated from above to group according to major to ultimately make a pie chart for this one

intapp.groupby('CCI Major').count()['Submission Date'].sort_values(ascending = False)

CCI Major
Visual Communication Design (BFA or BA)    250
Digital Media Production                   212
Journalism                                 119
Public Relations                            96
Communication Studies                       89
Emerging Media and Technology               70
Advertising                                 67
Photography                                 27
User Experience Design                       1
Name: Submission Date, dtype: int64

In [ ]:
#just going to copy what I did above
major_counts = intapp.groupby('CCI Major').size().sort_values(ascending=False)

In [ ]:

#found this in plotlygroup2's first pie chart and copied it over, now I'm cooking
fig2 = go.Figure(data=[go.Pie(labels=major_counts.index,values=major_counts.values,title="CCI Major Distribution")])

fig2.show()

In [126]:
intapp.groupby('Organization State').count()['Submission Date'].sort_values(ascending = False)[0:60]

Organization State
Ohio               726
California          32
New York            31
International       25
Pennsylvania        22
Massachusetts       11
Virginia             9
Wisconsin            7
Colorado             6
Georgia              6
Washington           6
Texas                6
Connecticut          5
Florida              5
Indiana              5
New Jersey           4
Arizona              3
Missouri             3
Michigan             3
Nevada               2
Maryland             2
Kentucky             2
Illinois             2
Washington D.C.      2
North Carolina       1
Maine                1
Oklahoma             1
Louisiana            1
Tennessee            1
Idaho                1
Name: Submission Date, dtype: int64

In [129]:
state_counts = intapp.groupby('Organization State').size().dropna()
state_counts = state_counts.head(20)
#again copied from above but I only want the top 20

In [130]:

#asked chatgpt: "Is there a formula to make a heat map in python with plotly" and I filled in the blanks since this is way above my skill level

fig3 = go.Figure(data=go.Choropleth(
    locations=state_counts.index,   # state abbreviations like OH, CA, NY
    z=state_counts.values,          # counts
    locationmode='USA-states',      # tells Plotly these are US states
    colorscale='Blues',
    colorbar_title="Submissions"
))

fig3.update_layout(
    title_text='Internship Submissions by State',
    geo_scope='usa'  # limits map to U.S.

)
fig3.update_layout(
    title='Internships by State',
    geo=dict(
        lakecolor='rgb(255, 255, 255)'
    ))
fig3.show()

In [ ]:
#I learned that it's blank because plotly only recognizes state abreviations for maps, and 
# my spreadsheet has full state names so I pulled this from chatgpt to clean it up
us_state_abbrev = {
    'Alabama': 'AL','Alaska': 'AK','Arizona': 'AZ','Arkansas': 'AR',
    'California': 'CA','Colorado': 'CO','Connecticut': 'CT','Delaware': 'DE',
    'Florida': 'FL','Georgia': 'GA','Hawaii': 'HI','Idaho': 'ID',
    'Illinois': 'IL','Indiana': 'IN','Iowa': 'IA','Kansas': 'KS',
    'Kentucky': 'KY','Louisiana': 'LA','Maine': 'ME','Maryland': 'MD',
    'Massachusetts': 'MA','Michigan': 'MI','Minnesota': 'MN',
    'Mississippi': 'MS','Missouri': 'MO','Montana': 'MT',
    'Nebraska': 'NE','Nevada': 'NV','New Hampshire': 'NH',
    'New Jersey': 'NJ','New Mexico': 'NM','New York': 'NY',
    'North Carolina': 'NC','North Dakota': 'ND','Ohio': 'OH',
    'Oklahoma': 'OK','Oregon': 'OR','Pennsylvania': 'PA',
    'Rhode Island': 'RI','South Carolina': 'SC','South Dakota': 'SD',
    'Tennessee': 'TN','Texas': 'TX','Utah': 'UT','Vermont': 'VT',
    'Virginia': 'VA','Washington': 'WA','West Virginia': 'WV',
    'Wisconsin': 'WI','Wyoming': 'WY'
}

# clean + convert
intapp['Organization State'] = intapp['Organization State'].str.strip()
intapp['State Abbrev'] = intapp['Organization State'].map(us_state_abbrev)

In [131]:
state_counts = intapp.groupby('State Abbrev').size().dropna()

In [136]:
fig3 = go.Figure(data=go.Choropleth(
    locations=state_counts.index,   # state abbreviations like OH, CA, NY
    z=state_counts.values,          # counts
    locationmode='USA-states',      # tells Plotly these are US states
    colorscale='Blues',
    colorbar_title="Submissions"
))

fig3.update_layout(
    title_text='Internship Submissions by State',
    geo_scope='usa'  # limits map to U.S.

)
fig3.update_layout(
    title='Internships by State',
    geo=dict(
        lakecolor='rgb(255, 255, 255)'
    ))
fig3.show()

In [ ]:
#not sure how to make this better. maybe expanding just the ohio and showing 
# where in ohio they are going would be of interest to econ dev groups. what would be interesting prospective families? current students? waht if I
#exclude ohio to make it less broad (1-32 outside of ohio)
#still need to figure out how to clean up that spreadsheet with company names too

final presentation 7-8 min, intro the problem you are trying to solve, talk about the process and why figures were chosen the way they were, limitations, etc. personal.kent.edu/
something about file zila